import express from 'express'
import morgan from 'morgan'
import path from 'path'
import bodyParser from 'body-parser'
import compression from 'compression'
import mongoose from 'mongoose'
import user from './routes/user'


let server, serverHttp
let port = 8080
let app = express()

//Connect to DB
mongoose.connect("mongodb://" + "fluorz:lecherbonnier1@ds349065.mlab.com:49065/area" , { useNewUrlParser: true })

server = app.listen(port, () => {console.log( "Express server listening on port " + port)})

app.use(compression())
app.use(bodyParser.json({limit: '50mb'}))
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}))
app.use(morgan("tiny"))

app.use((req, res, next) => {
	res.setHeader('Access-Control-Allow-Origin', '*')
	res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE')
	res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With, content-type, Authorization')
	next()
})

app.use('/user', user)
app.use('/authentification', user)

process.on('uncaughtException', err => {
	console.log(err)
})

app.get('/', (req, res) => {
	res.json("API Generated by sprint-package")
})

function stop() {
    server.close()
}

module.exports = app
module.exports.stop = stop
